### ISSUE TITLE
콘텐츠 예시 필요한 부분

### ISSUE THREAD

**Issue by Rory0304** [MoLab-SCT/MOLAB_Backend#1]
|페이지 이름|필요한 콘텐츠|개수|
|------|---|---|
|후기 페이지|사진 파일(PNG 형식) / 큰 제목 / 등록 날짜 / 전체 내용 / 가져온 링크|4|
|열린참여 페이지|공고 포스터(PNG 형식) / 큰 제목 / 신청 기간(시작 날짜~ 끝) / 모임 상세 정보 / 문의 기대평 / 관련 태그 /가져온 링크 |3|
|소통 페이지|큰 제목 / 작성인 / 등록 날짜 / 전체 내용 / 댓글 내용 / 댓글 개수 / 가져온 링크|4|

**Comment by cpti372** [comment]
https://drive.google.com/drive/folders/1IuR_VWSFwqsPMtJ_NW0zM1FVnAo_OTzR?usp=sharing
일단 여기 사진이랑 엑셀 파일 정리해놨습니다! 콘텐츠두용

**Comment by Rory0304** [comment]
넵 확인했습니다~ 감사합니다
